Repository alamin899/backend-api-task, pull requests merged in 2024-09, with the labels that each got.

#2 Migration ,model and reletionship implement
  app/Models/Order.php
  app/Models/OrderItem.php
  app/Models/Product.php
  app/Models/User.php
  database/migrations/2024_09_25_162434_create_products_table.php
  database/migrations/2024_09_25_162444_create_orders_table.php
  database/migrations/2024_09_25_162507_create_order_items_table.php
Labels: documentation, enhancement

#3 Product management from admin panel
  .gitignore
  app/Filament/Resources/ProductResource.php
  app/Filament/Resources/ProductResource/Pages/CreateProduct.php
  app/Filament/Resources/ProductResource/Pages/EditProduct.php
  app/Filament/Resources/ProductResource/Pages/ListProducts.php
  app/Models/Product.php
  app/Models/User.php
  app/Providers/Filament/AdminPanelProvider.php
  config/filament.php
  database/migrations/2024_09_25_162434_create_products_table.php
  database/migrations/2024_09_25_180547_add_user_type_field_to_users_table.php
  database/seeders/DatabaseSeeder.php
Labels: enhancement

#4 Product management from admin panel update
  app/Filament/Resources/ProductResource.php
  app/Providers/Filament/AdminPanelProvider.php
Labels: bug

#7 Product api functionality generated
  app/Domains/Product/Jobs/ProductCreateJob.php
  app/Domains/Product/Jobs/ProductListJob.php
  app/Domains/Product/Jobs/ProductUpdateJob.php
  app/Features/Auth/LogoutFeature.php
  app/Features/Product/ProductCreateFeature.php
  app/Features/Product/ProductListFeature.php
  app/Features/Product/ProductUpdateFeature.php
  app/Http/Controllers/API/Auth/LoginController.php
  app/Http/Controllers/API/Auth/LogoutController.php
  app/Http/Controllers/API/Auth/RefreshTokenController.php
  app/Http/Controllers/API/Auth/RegistrationController.php
  app/Http/Controllers/API/Product/ProductCreateController.php
  app/Http/Controllers/API/Product/ProductListController.php
  app/Http/Controllers/API/Product/ProductUpdateController.php
  app/Http/Middleware/IsAdminCheck.php
  app/Http/Requests/Auth/LoginRequest.php
  app/Http/Requests/Auth/RegistrationRequest.php
  app/Http/Requests/Product/CreateProductRequest.php
  app/Http/Requests/Product/UpdateProductRequest.php
  app/Http/Resources/ProductResource.php
  bootstrap/app.php
  database/factories/ProductFactory.php
  database/factories/UserFactory.php
  database/seeders/DatabaseSeeder.php
  database/seeders/ProductSeeder.php
  routes/api.php
Labels: documentation, enhancement

#8 Order management api
  app/Domains/Order/Jobs/OrderCreateJob.php
  app/Domains/Order/Jobs/OrderHistoryJob.php
  app/Domains/Order/Jobs/OrderProductCreateJob.php
  app/Domains/Order/Operations/PrepareOrderOperation.php
  app/Domains/Product/Jobs/ProductsBySlugsJob.php
  app/Features/Order/OrderCreateFeature.php
  app/Features/Order/OrderHistoryFeature.php
  app/Http/Controllers/API/Order/OrderCreateController.php
  app/Http/Controllers/API/Order/OrderHistoryController.php
  app/Http/Requests/Order/CreateOrderRequest.php
  app/Http/Resources/OrderItemResource.php
  app/Http/Resources/OrderResource.php
  app/Models/Order.php
  routes/api.php
Labels: enhancement

#9 [order-api] wp: postman collection
  apexdmit-api-task.postman_collection.json
Labels: enhancement

#11 missing filament package
  composer.json
Labels: bug

#12 GitHub prod build action
  README.md
  public/favicon.ico
  resources/views/welcome.blade.php
Labels: bug, documentation

#13 [home-page]refactor:version title updated
  resources/views/welcome.blade.php
Labels: documentation
